### ISSUE TITLE
Static files to s3 also?

### ISSUE THREAD

**Issue by peec** [arkadedigital/magento2-s3#3]
Are there any plans to support static files, such as static file deployment also?

Why? to offload servers

I believe some integration with https://github.com/magento/magento2/tree/develop/app/code/Magento/Deploy is needed.

**Comment by thaiphan** [comment]
I'll have a look and see what I can do.

**Comment by peec** [comment]
After a long though. I don't think this is needed actually. Static assets can be loaded through Cloudfront and thereby offloading the EC2s. So basically static assets are generated on each EC2 (if multi-server) and cloudfront takes care of loading the assets.

I am closing this for now, feel free to reopen if you still like to take a look at this.
