### ISSUE TITLE
Works in Magento 2.1?

### ISSUE THREAD

**Issue by gerandoblogs** [arkadedigital/magento2-s3#31]
Works in Magento 2.1?

**Comment by tejaspatel2014** [comment]
Hi,

We have tested it on Magento 2.1

Regards

**Comment by gerandoblogs** [comment]
Thanks for the extension and the quick response ... but I have only one question! Is it necessary to configure base url (using cloudfront) in the admin panel magento? Or does this extension already do this cdn job?
