### ISSUE TITLE
how to do the rewrite

### ISSUE THREAD

**Issue by chong1227** [arkadedigital/magento2-s3#4]
this is the localhost url http://www.maravale.com/pub/media/catalog/product/cache/1/image/1000x1240/e9c3970ab036de70892d86c6d221abfe/_/2/_2015-10-15_02.28.40.png

this is the s3 url
https://s3-sa-east-1.amazonaws.com/maravale/catalog/product/cache/1/image/1000x1240/e9c3970ab036de70892d86c6d221abfe/_/2/_2015-10-15_02.28.40.png

**Comment by chong1227** [comment]
it is same pic.

**Comment by thaiphan** [comment]
Hey @chong1227,

Do you want to host your images directly from S3 or CloudFront? Or are you just planning on using S3 as a file storage backend?

**Comment by chong1227** [comment]
i see i can't explain in english.~~~ em, i thought your extension is not work... but now i know it is has a great work!!!

**Comment by chong1227** [comment]
http://www.maravale.com/pub/media/catalog/product/cache/1/image/1000x1240/e9c3970ab036de70892d86c6d221abfe/_/2/_2015-10-15_02.28.40.png  this url's host is our website but it rewrite to S3 host~~~

**Comment by chong1227** [comment]
do u understand my chinese english??~~~

**Comment by chong1227** [comment]
;)

**Comment by thaiphan** [comment]
Hey @chong1227,

So do you still have problems? You can the media URL via the Magento backend if you want to switch to using S3 that way! I'm just worried that thumbnails on product and category pages won't get generated properly. Please advise if you still need help.

**Comment by thaiphan** [comment]
Hey @chong1227,

I'm closing this ticket. As I've stated, you don't need to do any web server rewrites. I've updated the wiki to remove any confusion. You can change your media URL using the system configuration!

![Magento admin panel](http://i.imgur.com/3IZQp8A.png)

Feel free to open up a new ticket if you run into any other problems.
