### ISSUE TITLE
Installation Step #3

### ISSUE THREAD

**Issue by bert-teng** [arkadedigital/magento2-s3#6]
Not really an issue but more of an suggestion.

For your [Step 3 - Update config.php](https://github.com/arkadedigital/magento2-s3/wiki/Installation-%28Command-Line%29#step-3---update-configphp)
You could do the following and it will enable your module and update the config.php file at the same time
```
php ./bin/magento module:enable Arkade_S3
```

I figure this would be easier and less error prone than directly editing the config.php file

**Comment by thaiphan** [comment]
Hey @bert-teng,

Thanks for the tip! I've didn't know this feature existed. I'll have to have a look at it tonight to see if that command also makes Step 4 unnecessary.

Regards,

Thai

**Comment by bert-teng** [comment]
Yea, you still do. In fact after running
```
php ./bin/magento setup:upgrade
```
At the end it actually ask you to "re-run Magento compile command", which is as follows:
```
php ./bin/magento setup:di:compile
```

**Comment by thaiphan** [comment]
Hey @bert-teng,

I've updated the wiki. Thanks for the tip!

Regards,

Thai
