### ISSUE TITLE
After Sync. Upload new product images S3 permission issue

### ISSUE THREAD

**Issue by lgjackhuang** [arkadedigital/magento2-s3#7]
I got 403 after upload the image.

then, I found new image's permission have no everyone Open/Download in S3.

I don't know which part I get wrong.
I installed this ext via command. all media can sync to S3 but 403.

Reading your code... I found u added 'public-read' on save.

**Comment by thaiphan** [comment]
Hey @lgjackhuang,

Uh, are you using the S3 domain now for your media URL?

Regards,

Thai

**Comment by lgjackhuang** [comment]
Hi,

My problem resolved.

Yes sure. 
In configure, I change the media path use s3 so all image pointing to s3.

After I google search.
I found out I made mistake on s3 policy. I added a s3 policy let all content in s3 default public access.

Best regards,
Jack.



從我的 iPhone 傳送

**Comment by thaiphan** [comment]
Hey @lgjackhuang,

Cool thanks. I hope you enjoy my extension! Please don't hesitate to create another issue if you come across anything else.

Regards,

Thai
