### ISSUE TITLE
Update "Base URL for User Media Files" generates error

### ISSUE THREAD

**Issue by aaronsturm** [arkadedigital/magento2-s3#8]
I was able to set "Base URL for User Media Files" in Stores->Configuration->General->Web before I installed the plugin. After I installed the plugin, I get this error every time I try and change that field. More specifically, I tried to change that field to {{unsecure_base_url}} or just leaving it blank.

`Fatal error: Uncaught Error: Call to a member function deleteFolder() on null in /var/www/html/vendor/magento/module-media-storage/Helper/File/Storage/Database.php:261 Stack trace: #0 /var/www/html/var/generation/Magento/MediaStorage/Helper/File/Storage/Database/Interceptor.php(167): Magento\MediaStorage\Helper\File\Storage\Database->deleteFolder('/var/www/html/p...') #1 /var/www/html/vendor/magento/module-media-storage/Model/Asset/Plugin/CleanMergedJsCss.php(51): Magento\MediaStorage\Helper\File\Storage\Database\Interceptor->deleteFolder('/var/www/html/p...') #2 [internal function]: Magento\MediaStorage\Model\Asset\Plugin\CleanMergedJsCss->aroundCleanMergedJsCss(Object(Magento\Framework\View\Asset\MergeService\Interceptor), Object(Closure)) #3 /var/www/html/vendor/magento/framework/Interception/Interceptor.php(140): call_user_func_array(Array, Array) #4 /var/www/html/var/generation/Magento/Framework/View/Asset/MergeService/Interceptor.php(39): Magento\Framework\View\Asset\MergeService\Interceptor->___callPlugins('cleanMe in /var/www/html/vendor/magento/module-media-storage/Helper/File/Storage/Database.php on line 261`

This extension seems to work well otherwise and I appreciate your efforts to create and share it! Thank you!

**Comment by thaiphan** [comment]
Hey @aaronsturm,

Thanks for using my extension! I'll have a look tonight and see what's up!

Regards,

Thai

**Comment by thaiphan** [comment]
Hey @aaronsturm,

I've pushed up an update that should fix the problem that you were having. Can you update to the latest version of the extension and check everything is now working?

Regards,

Thai

**Comment by jackhuang89** [comment]
ha. I tried latest version of extension. composer install is fine.  No red text anymore.

**Comment by aaronsturm** [comment]
It worked! Thanks so much!!
