### ISSUE TITLE
Vimeo / Youtube Media Files S3 404

### ISSUE THREAD

**Issue by jackhuang89** [arkadedigital/magento2-s3#9]
um.. I think we should support this files upload.

is it support right now?

external-video

<img width="1330" alt="screen shot 2016-04-14 at 5 03 53 pm" src="https://cloud.githubusercontent.com/assets/3734296/14522806/eac11af6-0262-11e6-8b6b-aba54c4c04fc.png">

**Comment by thaiphan** [comment]
Hey @jackhuang89,

I'm pretty sure Magento 2 only lets you link to external services like YouTube and Vimeo. Built-in video support sounds like it would be out of scope for this extension sorry. :(

Regards,

Thai

**Comment by jackhuang89** [comment]
Hi,

Video link to external is correct But the preview image and thumb image is trying to fetch from s3
And s3 response 404. 

I temp disable the video right now until I enhance something to support it with s3.

Regards,
Jack

從我的 iPhone 傳送

**Comment by thaiphan** [comment]
Hey @jackhuang89,

Oh okay, I understand you now! Sorry! Yeah okay, I'll have a look see.

Regards,

Thai

**Comment by thaiphan** [comment]
Hey @jackhuang89,

Are you still there? Yeah, I identified the problem as a core Magento bug. I've made a pull request [here](https://github.com/magento/magento2/pull/4258).

In the meantime, I've released v1.1.5 of this extension, which should also address your problem!

Can you advise whether product video thumbnails are working now?

Regards,

Thai

**Comment by jackhuang89** [comment]
Yo @thaiphan,

I am here, I installed a brand new magento 2.0.4 and your extension 1.1.5.

The issue resolved.

Admin Panel:

<img width="1611" alt="screen shot 2016-04-22 at 6 01 02 pm" src="https://cloud.githubusercontent.com/assets/3734296/14738529/a2222670-08b4-11e6-867a-32a2c3a93f88.png">

Front-end:
<img width="1130" alt="screen shot 2016-04-22 at 6 04 43 pm" src="https://cloud.githubusercontent.com/assets/3734296/14738545/b9629a54-08b4-11e6-8e73-34ff8d79804f.png">
